### ISSUE TITLE
Music Stand Desktop is not responding

### ISSUE THREAD

**Issue by robsharpGFW** [martijnversluis/pco-musicstand-midi-control-chrome-extension#11]
I have recorded Previous and Next slides, but the app does not seem to be responding.

**Comment by martijnversluis** [comment]
Hey @robsharpGFW. Thanks for your reporting your issue.

Could you provide me with the following to have some info for debugging:

- some basic info like OS, browser and browser version
- a screenshot of the options page
- a screenshot (or even a screen recording if possible) of the working application. 
  1. Make sure you open a service that has multiple pages in MusicStand
  2. Open your browser's debugging tools. See instructions [here](https://developer.chrome.com/docs/devtools/open/) how to open. Make sure you activate the  `Console` tab. Then use your MIDI device to trigger the exact MIDI messages you configured and record the incoming messages in the developer console.

You can post the info here in the thread, or send me a DM on [Twitter](https://twitter.com/martijnversluis).

Note: when changing options for the extension you need to reload any MusicStand browser tab to activate changes.

**Comment by robsharpGFW** [comment]
I got it working just had to reboot music stand. I thought I had done that, but apparently not.

Thanks,

Rob Sharp

Geared For Worship
318-230-1308
gearedforworship.com

**Comment by martijnversluis** [comment]
Great! Thanks for reaching out anyway 👍
